name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO
        id: build-iso
        uses: zeglius/titanoboa@compose-action
        with:
          image-ref: ghcr.io/ublue-os/bluefin:lts
